# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

workspace 'LikemindsChatSample.xcworkspace'

target 'LikemindsChatSample' do
  project 'LikemindsChatSample.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LikemindsChatSample
 pod 'LikeMindsChat', path: '/Users/pushpendra/likeminds_workspace/GroupChatV2/LikeMindsChat/LikeMinds-iOS-Chat-SDK/LikeMindsChat.podspec'
 pod 'LMChatUI_iOS', path: '../LMChatUI_iOS/LMChatUI_iOS.podspec'
 pod 'LMChatCore_iOS', path: '../LMChatCore_iOS/LMChatCore_iOS.podspec'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end